
name: CI/CD para ML con MLflow

on:
  push:
    branches: [main]

jobs:
  ml_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Clonar repositorio
        uses: actions/checkout@v3

      - name: ðŸ“¥ Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: ðŸ“¥ Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow joblib scikit-learn pandas

      - name: ðŸ“¥ Entrenar modelo
        run: make train

      # - name: Validar desempeÃ±o del modeloâœ…
      #   run: make validate
      # - name: ðŸ“¥ Subir modelo como artefacto (si pasa validaciÃ³n)
      #   if: success()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: modelo-validado
      #     path: model.pkl
      # ddd
